trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: dotnet restore
  - script: dotnet test ./test/Certes.Tests/Certes.Tests.csproj --framework netcoreapp2.1
  - script: dotnet test ./test/Certes.Tests/Certes.Tests.Integration.csproj --framework netcoreapp2.1
