jobs:
- job: Ubuntu
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
      workingDirectory: './'
